import { COMMANDS, type CommandSpec } from './commands';

const fnName = (bin: string) => `_${bin.replace(/-/g, '_')}`;

const escape = (s: string) => s.replace(/[\\"$`]/g, '\\$&');

const emitCase = (label: string, flags: string[], compgenArg: string): string => {
  if (flags.length === 0) return '';
  return `    ${flags.join('|')}) mapfile -t COMPREPLY < <(compgen -${compgenArg} -- "$cur"); compopt -o filenames; return ;;  # ${label}`;
};

const emitCommand = (spec: CommandSpec): string => {
  const fn = fnName(spec.bin);
  const cases = [emitCase('file flags', spec.fileFlags, 'f'), emitCase('dir flags', spec.dirFlags, 'd')]
    .filter(Boolean)
    .join('\n');

  const flagCompletion = spec.flags
    ? `  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "${escape(spec.flags)}" -- "$cur"))
    return
  fi`
    : '';

  const positional =
    spec.positional === 'dir'
      ? `  mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames`
      : spec.positional === 'file'
        ? `  mapfile -t COMPREPLY < <(compgen -f -- "$cur"); compopt -o filenames`
        : `  COMPREPLY=()`;

  return `${fn}() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
${cases || '    "") ;;'}
  esac
${flagCompletion}
${positional}
}
complete -F ${fn} ${spec.bin}`;
};

/** Generate the unified `mu` / `music-utils` subcommand completion. */
const generateUnifiedBash = (): string => `_mu() {
  local cur prev cmd sub
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]}"
  sub="\${COMP_WORDS[2]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=($(compgen -W "rip tag cover sync similarities audit completion help" -- "$cur"))
    return
  fi

  if [[ $COMP_CWORD -eq 2 ]]; then
    case "$cmd" in
      tag)   COMPREPLY=($(compgen -W "album tracks bulk" -- "$cur")); return ;;
      cover) COMPREPLY=($(compgen -W "album bulk" -- "$cur")); return ;;
      audit) COMPREPLY=($(compgen -W "repair retag" -- "$cur")); return ;;
    esac
  fi

  case "$cmd" in
    rip)
      COMPREPLY=($(compgen -W "--releaseId -r --disc -d" -- "$cur")) ;;
    tag)
      case "$sub" in
        album)
          case "$prev" in
            -a|--album) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
          esac
          COMPREPLY=($(compgen -W "-a --album" -- "$cur")) ;;
        tracks)
          case "$prev" in
            -a|--album) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
            -f|--fileName) mapfile -t COMPREPLY < <(compgen -f -- "$cur"); compopt -o filenames; return ;;
          esac
          COMPREPLY=($(compgen -W "-a --album -f --fileName" -- "$cur")) ;;
        bulk)
          mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames ;;
      esac ;;
    cover)
      case "$sub" in
        album)
          case "$prev" in
            -a|--album) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
          esac
          COMPREPLY=($(compgen -W "-a --album" -- "$cur")) ;;
        bulk)
          mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames ;;
        *)
          case "$prev" in
            -a|--album) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
          esac
          COMPREPLY=($(compgen -W "-a --album -r --releaseId -Q --quiet" -- "$cur")) ;;
      esac ;;
    sync)
      case "$prev" in
        -a|--album) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
      esac
      COMPREPLY=($(compgen -W "-a --album" -- "$cur")) ;;
    similarities)
      case "$prev" in
        -A|--dirA|-B|--dirB) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
        -f|--fileName) mapfile -t COMPREPLY < <(compgen -f -- "$cur"); compopt -o filenames; return ;;
      esac
      COMPREPLY=($(compgen -W "-A --dirA -B --dirB -T --threshold -f --fileName -I --ignore -Q --quiet" -- "$cur")) ;;
    audit)
      case "$prev" in
        --root) mapfile -t COMPREPLY < <(compgen -d -- "$cur"); compopt -o filenames; return ;;
      esac
      COMPREPLY=($(compgen -W "--root --token --no-discogs --repair --retag --ui --json --log --help" -- "$cur")) ;;
    completion)
      COMPREPLY=($(compgen -W "bash" -- "$cur")) ;;
  esac
}
complete -F _mu mu
complete -F _mu music-utils`;

/** Generate a bash completion script for every `music-utils-*` CLI and the unified `mu` CLI. */
export const generateBash = (): string => {
  const header = `# music-utils bash completion — generated by \`mu completion bash\`
# Install (session):    source <(mu completion bash)
# Install (persistent): mu completion bash > ~/.local/share/bash-completion/completions/music-utils
`;
  return `${header}\n${COMMANDS.map(emitCommand).join('\n\n')}\n\n${generateUnifiedBash()}\n`;
};
