import { COMMANDS, type CommandSpec } from './commands';

const fnName = (bin: string) => `_${bin.replace(/-/g, '_')}`;

const escape = (s: string) => s.replace(/[\\"$`]/g, '\\$&');

const emitCase = (label: string, flags: string[], compgenArg: string): string => {
  if (flags.length === 0) return '';
  return `    ${flags.join('|')}) COMPREPLY=($(compgen -${compgenArg} -- "$cur")); return ;;  # ${label}`;
};

const emitCommand = (spec: CommandSpec): string => {
  const fn = fnName(spec.bin);
  const cases = [emitCase('file flags', spec.fileFlags, 'f'), emitCase('dir flags', spec.dirFlags, 'd')]
    .filter(Boolean)
    .join('\n');

  const flagCompletion = spec.flags
    ? `  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "${escape(spec.flags)}" -- "$cur"))
    return
  fi`
    : '';

  const positional =
    spec.positional === 'dir'
      ? `  COMPREPLY=($(compgen -d -- "$cur"))`
      : spec.positional === 'file'
        ? `  COMPREPLY=($(compgen -f -- "$cur"))`
        : `  COMPREPLY=()`;

  return `${fn}() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
${cases || '    "") ;;'}
  esac
${flagCompletion}
${positional}
}
complete -F ${fn} ${spec.bin}`;
};

/** Generate a bash completion script for every `music-utils-*` CLI. */
export const generateBash = (): string => {
  const header = `# music-utils bash completion — generated by \`music-utils-completion bash\`
# Install (session):    source <(music-utils-completion bash)
# Install (persistent): music-utils-completion bash > ~/.local/share/bash-completion/completions/music-utils
`;
  return `${header}\n${COMMANDS.map(emitCommand).join('\n\n')}\n`;
};
