# .github/workflows/[your_workflow].yml


name: NodeJS with Webpack

on:
  push:
    branches: ['main'] 
jobs:
  bump:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.X]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag-prefix:  'v'
            commit-message: 'CI: bumps version to {{version}}'
